MAX_THREADS = 4

BASE_OUTPUT_DIR = "./output/IJCAI"

BASE_SKETCH_DIR = 'models/pomdp/sketches'

USE_SAYNT_HOTFIX = True
SAYNT_MEMORY_MODEL_TIMEOUT = 30
SAYNT_MEMORY_MODEL_SUBFAM_SIZE   = 10

OVERWRITE_EXISTING_RESULTS = False

MAX_NUM_NODES = 5
MAX_ITER = int(1e99)

TIMEOUT=3600
SUBFAMILY_SIZE=10
SEED=11

SAYNT_MEMORY_MODEL_SUBFAM_SIZE = min(SAYNT_MEMORY_MODEL_SUBFAM_SIZE, SUBFAMILY_SIZE)

# illustrative example settings
EXAMPLE_SEED=11
EXAMPLE_SUBFAMILY_SIZE=3
EXAMPLE_TIMEOUT=SUBFAMILY_SIZE*10

# WIP models, might get deleted:
ACO = f"{BASE_SKETCH_DIR}/aco"
INTERCEPT = f"{BASE_SKETCH_DIR}/intercept"

# Can try various models.
OBSTACLES_EIGHTH_THREE = f"{BASE_SKETCH_DIR}/obstacles-8-5"
OBSTACLES_TEN_TWO = f"{BASE_SKETCH_DIR}/obstacles-10-2"
AVOID = f"{BASE_SKETCH_DIR}/avoid"
DPM = f"{BASE_SKETCH_DIR}/dpm"
ROVER = f"{BASE_SKETCH_DIR}/rover"
NETWORK = f"{BASE_SKETCH_DIR}/network"
ILLUSTRATIVE = f"{BASE_SKETCH_DIR}/obstacles-illustrative"

POSSIBLE_ENVS = [OBSTACLES_TEN_TWO, OBSTACLES_EIGHTH_THREE, DPM, AVOID, ROVER, NETWORK, ILLUSTRATIVE]

# Environments to run
ENVS = [OBSTACLES_TEN_TWO, OBSTACLES_EIGHTH_THREE, ROVER, DPM, AVOID, NETWORK]
